// Fiches (juridictions, organismes, textes, traitements fiscaux, lexique), références (sources, agenda, auteurs)
// et classements de l'éditeur. Mêmes clés que les schémas Zod (src/lib/content/schemas.ts).
import { collection, fields } from '@keystatic/core';
import legal from '../../../config/legal.json' with { type: 'json' };
import {
  AGENDA_TYPE,
  AUTHORITY_TYPE,
  CATEGORY_BADGE,
  JURISDICTION_BADGE,
  JURISDICTION_LEVEL,
  LEGAL_STATUS,
  SCHEMA_TYPE,
  SOCIAL_NETWORK,
  SOURCE_TYPE,
  TAX_TYPE,
  TEXT_TYPE,
  THEME_GROUP,
} from '../content/enums.ts';
import { body, seo } from './collections-editorial.ts';
import * as f from './fields.ts';
import { heading } from './heading.ts';
import { image } from './images.ts';
import type { CollectionName } from '../content/collections.ts';
import { collectionLabel, labelled } from './labels.ts';
import messages from '../../../config/i18n/fr.json' with { type: 'json' };

const mdx = { contentField: 'body' } as const;
const json = { data: 'json' } as const;
const publication = () => ({ _publication: heading('publication'), status: f.status() });
const referencement = (collection: CollectionName) => ({ _referencement: heading('referencement'), seo: seo(collection), ...f.reserved() });

const socialOptions = SOCIAL_NETWORK.map((value) => ({ label: (messages.social as Record<string, string>)[value] ?? value, value }));

// Taxonomie simple : libellé, description, ordre.
const taxonomy = (name: 'activites' | 'contribuables' | 'themes' | 'formats', path: string, extra: Record<string, ReturnType<typeof f.text>> = {}) =>
  collection({
    label: collectionLabel(name),
    path: `content/taxonomies/${path}/*`,
    slugField: 'label',
    format: json,
    columns: ['label', 'order'],
    schema: { label: f.slugField('label', undefined, { min: 2 }), description: f.text('description', undefined, { multiline: true }), ...extra, order: f.integer('order', undefined, { defaultValue: 100 }) },
  });

export const referenceCollections = {
  juridictions: collection({
    label: collectionLabel('juridictions'),
    path: 'content/juridictions/*',
    slugField: 'name',
    format: mdx,
    columns: ['name', 'level', 'status'],
    previewUrl: '/juridictions/{slug}/',
    schema: {
      name: f.slugField('name', 'juridictions', { min: 2 }),
      level: f.choice('level', 'jurisdictionLevel', JURISDICTION_LEVEL, 'federal', 'juridictions'),
      country: f.text('country'),
      description: f.text('description', undefined, { multiline: true, required: true, length: { max: 300 } }),
      body: body('juridictions'),
      faq: f.faq(),
      _affichage: heading('affichage'),
      icon: f.icon(),
      order: f.integer('order', undefined, { defaultValue: 100 }),
      parent: f.relation('parent', 'juridictions'),
      badgeStyle: f.select('badgeStyle', 'jurisdictionBadge', JURISDICTION_BADGE, 'contour'),
      _relations: heading('relations'),
      keyDossiers: f.relations('keyDossiers', 'dossiers'),
      keyTraitements: f.relations('keyTraitements', 'traitements'),
      ...publication(),
      ...referencement('juridictions'),
    },
  }),
  organismes: collection({
    label: collectionLabel('organismes'),
    path: 'content/organismes/*',
    slugField: 'name',
    format: mdx,
    columns: ['name', 'acronym', 'status'],
    previewUrl: '/organismes/{slug}/',
    schema: {
      name: f.slugField('name', 'organismes', { min: 2 }),
      acronym: f.text('acronym'),
      jurisdiction: f.relation('jurisdiction', 'juridictions', undefined, true),
      authorityType: f.choice('authorityType', 'authorityType', AUTHORITY_TYPE, 'autre'),
      role: f.text('role', undefined, { multiline: true, required: true, length: { max: 300 } }),
      website: f.url('website', undefined, true),
      logo: image('logo', 'organismes', 'organismes'),
      body: body('organismes'),
      _revision: heading('revision'),
      asOf: f.date('asOf'),
      ...publication(),
      ...referencement('organismes'),
    },
  }),
  textes: collection({
    label: collectionLabel('textes'),
    path: 'content/textes/*',
    slugField: 'title',
    format: mdx,
    columns: ['title', 'type', 'status'],
    previewUrl: '/textes/{slug}/',
    schema: {
      title: f.slugField('title', 'textes', { min: 5, max: 200 }),
      shortTitle: f.text('shortTitle'),
      summary: f.text('summary', 'textes', { multiline: true, required: true, length: { max: 400 } }),
      keyProvisions: f.textList('keyProvisions'),
      body: body('textes'),
      _reglementation: heading('reglementation'),
      type: f.choice('type', 'textType', TEXT_TYPE, 'loi', 'textes'),
      issuer: f.relation('issuer', 'organismes', undefined, true),
      jurisdiction: f.relation('jurisdiction', 'juridictions', undefined, true),
      legalStatus: f.choice('legalStatus', 'legalStatus', LEGAL_STATUS),
      documentNumber: f.text('documentNumber'),
      citation: f.text('citation'),
      adoptedAt: f.date('adoptedAt'),
      inForceAt: f.date('inForceAt'),
      _sources: heading('sources'),
      officialUrl: f.url('officialUrl', undefined, true),
      archivedUrl: f.url('archivedUrl'),
      _revision: heading('revision'),
      asOf: f.date('asOf'),
      ...publication(),
      ...referencement('textes'),
    },
  }),
  traitements: collection({
    label: collectionLabel('traitements'),
    path: 'content/traitements-fiscaux/*',
    slugField: 'title',
    format: mdx,
    columns: ['title', 'status'],
    previewUrl: '/fiscalite/traitements/{slug}/',
    schema: {
      title: f.slugField('title', 'traitements', { min: 10, max: 160 }),
      treatment: f.text('treatment', undefined, { multiline: true, required: true }),
      body: body('traitements'),
      _fiscalite: heading('fiscalite'),
      jurisdiction: f.relation('jurisdiction', 'juridictions', undefined, true),
      taxpayerType: f.relation('taxpayerType', 'contribuables', undefined, true),
      activity: f.relation('activity', 'activites', undefined, true),
      taxType: f.choice('taxType', 'taxType', TAX_TYPE, 'impot-revenu'),
      taxableEvent: f.text('taxableEvent', undefined, { multiline: true }),
      reportingRequirement: f.text('reportingRequirement', undefined, { multiline: true }),
      forms: fields.array(fields.object({ code: f.text('code', undefined, { required: true }), name: f.text('name', 'forms', { required: true }), url: f.url('url') }), {
        ...labelled('forms'),
        itemLabel: (props) => `${props.fields.code.value} ${props.fields.name.value}`,
      }),
      _sources: heading('sources'),
      sources: f.sources(),
      _revision: heading('revision'),
      asOf: f.date('asOf'),
      reviewEvery: f.reviewEvery(),
      ...publication(),
      publishedAt: f.date('publishedAt'),
      updatedAt: f.date('updatedAt'),
      ...referencement('traitements'),
    },
  }),
  lexique: collection({
    label: collectionLabel('lexique'),
    path: 'content/lexique/*',
    slugField: 'term',
    format: mdx,
    columns: ['term', 'status'],
    previewUrl: '/lexique/{slug}/',
    schema: {
      term: f.slugField('term'),
      shortDefinition: f.text('shortDefinition', undefined, { multiline: true, required: true, length: { max: 200 } }),
      synonyms: f.textList('synonyms'),
      body: body('lexique'),
      _relations: heading('relations'),
      seeAlso: f.relations('seeAlso', 'lexique'),
      officialSources: f.sources('officialSources'),
      ...publication(),
      ...referencement('lexique'),
    },
  }),
  sources: collection({
    label: collectionLabel('sources'),
    path: 'content/sources/*',
    slugField: 'title',
    format: json,
    columns: ['title', 'sourceType'],
    schema: {
      title: f.slugField('title'),
      sourceType: f.pick('sourceType', 'sourceType', SOURCE_TYPE),
      url: f.url('url', undefined, true),
      archivedUrl: f.url('archivedUrl'),
      issuer: f.relation('issuer', 'organismes'),
      issuerLabel: f.text('issuerLabel'),
      jurisdiction: f.relation('jurisdiction', 'juridictions'),
      documentDate: f.date('documentDate'),
      accessedDate: f.date('accessedDate'),
      documentNumber: f.text('documentNumber'),
      citation: f.text('citation'),
    },
  }),
  agenda: collection({
    label: collectionLabel('agenda'),
    path: 'content/agenda/*',
    slugField: 'title',
    format: json,
    columns: ['title', 'date', 'status'],
    previewUrl: '/agenda/',
    schema: {
      title: f.slugField('title'),
      type: f.choice('type', 'agendaType', AGENDA_TYPE, 'echeance-fiscale', 'agenda'),
      date: f.date('date', undefined, true),
      endDate: f.date('endDate'),
      time: f.optionalTime('time'),
      jurisdiction: f.relation('jurisdiction', 'juridictions', undefined, true),
      description: f.text('description', 'agenda', { multiline: true }),
      url: f.url('url'),
      relatedDossier: f.relation('relatedDossier', 'dossiers'),
      status: f.status(),
    },
  }),
  auteurs: collection({
    label: collectionLabel('auteurs'),
    path: 'content/auteurs/*',
    slugField: 'name',
    format: json,
    columns: ['name', 'role'],
    previewUrl: '/auteurs/{slug}/',
    schema: {
      name: f.slugField('name', undefined, { min: 2 }),
      role: f.text('role'),
      avatar: image('avatar', 'auteurs'),
      bio: f.text('bio', undefined, { multiline: true }),
      mentionProfessionnelle: f.text('mentionProfessionnelle'),
      socials: fields.array(fields.object({ network: fields.select({ ...labelled('network'), options: socialOptions, defaultValue: 'linkedin' }), url: f.link('url') }), {
        ...labelled('socials'),
        itemLabel: (props) => props.fields.network.value,
      }),
      active: f.checkbox('active', true),
    },
  }),
  categories: collection({
    label: collectionLabel('categories'),
    path: 'content/taxonomies/categories/*',
    slugField: 'label',
    format: json,
    columns: ['label', 'order'],
    previewUrl: '/{slug}/',
    schema: {
      label: f.slugField('label', undefined, { min: 2 }),
      description: f.text('description', undefined, { multiline: true, required: true, length: { max: 300 } }),
      badgeStyle: f.select('badgeStyle', 'categoryBadge', CATEGORY_BADGE, 'plein-500'),
      icon: f.icon(),
      order: f.integer('order', undefined, { defaultValue: 100 }),
      requireVerification: f.checkbox('requireVerification', false),
      defaultDisclaimer: f.disclaimer('defaultDisclaimer', legal.disclaimers),
    },
  }),
  themes: taxonomy('themes', 'themes', { group: f.select('group', 'themeGroup', THEME_GROUP, 'general') } as unknown as Record<string, ReturnType<typeof f.text>>),
  formats: taxonomy('formats', 'formats', { schemaType: f.select('schemaType', 'schemaType', SCHEMA_TYPE, 'NewsArticle') } as unknown as Record<string, ReturnType<typeof f.text>>),
  activites: taxonomy('activites', 'activites-fiscales'),
  contribuables: taxonomy('contribuables', 'types-contribuables'),
};

