// Liste fermée des icônes Lucide utilisables dans la configuration et le contenu
// (menus, taxonomies, encadrés). Le composant Icon.astro fait la correspondance nom → dessin.
export const ICON_NAMES = [
  'archive',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-up-right',
  'badge-alert',
  'badge-check',
  'book-open',
  'bookmark',
  'briefcase-business',
  'building',
  'building-complex',
  'calculator',
  'calendar',
  'calendar-clock',
  'calendar-plus',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'circle-alert',
  'circle-check',
  'circle-dashed',
  'circle-slash',
  'clock',
  'coins',
  'copy',
  'download',
  'external-link',
  'eye',
  'file-pen',
  'file-text',
  'flag',
  'folder-open',
  'funnel',
  'gavel',
  'git-compare',
  'globe',
  'graduation-cap',
  'hand-coins',
  'hash',
  'house',
  'info',
  'landmark',
  'library',
  'lightbulb',
  'link',
  'list',
  'list-checks',
  'list-ordered',
  'mail',
  'map-pin',
  'menu',
  'messages-square',
  'moon',
  'newspaper',
  'pencil-line',
  'play',
  'printer',
  'quote',
  'radio-tower',
  'receipt',
  'refresh-cw',
  'rss',
  'scale',
  'scroll-text',
  'search',
  'send',
  'share-2',
  'shield-check',
  'sparkles',
  'stamp',
  'sun',
  'table-of-contents',
  'tag',
  'trending-down',
  'trending-up',
  'triangle-alert',
  'user',
  'users',
  'x',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export function isIconName(value: string): value is IconName {
  return (ICON_NAMES as readonly string[]).includes(value);
}
